/**
 * Example prompts for goal extraction (v1)
 * Used for few-shot learning - can be versioned and A/B tested
 */

export const GOAL_EXTRACTION_EXAMPLES_V1 = [
  '**Examples:**',
  '',
  '// User: "Schedule a call with jane@acme.com tomorrow at 3pm for 30 minutes"',
  '{',
  '  "outcome": "Schedule a meeting with jane@acme.com",',
  '  "context": {',
  '    "who": "jane@acme.com",',
  '    "when": "tomorrow at 3pm",',
  '    "what": "call"',
  '  },',
  '  "provided": {',
  '    "attendee_email": "jane@acme.com",',
  '    "duration_minutes": 30,',
  '    "relative_time": "tomorrow at 3pm"',
  '  },',
  '  "missing": [],',
  '  "success_criteria": "Meeting scheduled and attendee notified",',
  '  "confidence": 0.95',
  '}',
  '',
  '// User: "Draft follow-up emails for no-reply threads from the last 7 days"',
  '{',
  '  "outcome": "Create polite follow-up drafts for no-reply threads from the last 7 days",',
  '  "context": {',
  '    "what": "no-reply threads",',
  '    "when": "last 7 days",',
  '    "constraints": ["Only threads with no replies", "Timeframe: last 7 days"]',
  '  },',
  '  "provided": {',
  '    "days": 7',
  '  },',
  '  "missing": [],',
  '  "success_criteria": "Polite follow-up drafts are created for all no-reply threads from the last 7 days",',
  '  "confidence": 0.95',
  '}',
  '',
  '// User: "Post to LinkedIn about our new feature"',
  '{',
  '  "outcome": "Create and publish a LinkedIn post about a new feature",',
  '  "context": {',
  '    "where": "LinkedIn",',
  '    "what": "post about new feature"',
  '  },',
  '  "provided": {',
  '    "platform": "linkedin",',
  '    "topic": "new feature"',
  '  },',
  '  "missing": [',
  '    { "key": "content", "question": "What should the post say?", "type": "text", "required": true }',
  '  ],',
  '  "confidence": 0.8',
  '}',
  '',
  '// User: "Give me a 10-minute triage of priority emails and create quick-reply drafts (max 8)"',
  '{',
  '  "outcome": "Triage priority emails from the last 10 minutes and create up to 8 quick-reply drafts",',
  '  "context": {',
  '    "what": "priority emails needing replies",',
  '    "when": "last 10 minutes",',
  '    "constraints": ["max 8 drafts", "quick replies"]',
  '  },',
  '  "provided": {',
  '    "time_window_minutes": 10,',
  '    "max_results": 8,',
  '    "action_type": "triage_and_draft"',
  '  },',
  '  "missing": [',
  '    { "key": "priority_criteria", "question": "What makes an email priority? (e.g., from specific senders, keywords like urgent, has attachments)", "type": "text", "required": false },',
  '    { "key": "reply_tone", "question": "Preferred tone for replies?", "type": "select", "required": false, "options": ["professional", "casual", "friendly"] }',
  '  ],',
  '  "success_criteria": "Up to 8 draft replies created for priority emails from the last 10 minutes",',
  '  "confidence": 0.9',
  '}',
].join('\n');
