/**
 * Example prompts for goal extraction (v1)
 * Used for few-shot learning - can be versioned and A/B tested
 */

export const GOAL_EXTRACTION_EXAMPLES_V1 = [
  '**Examples:**',
  '',
  '// User: "Schedule a call with jane@acme.com tomorrow at 3pm for 30 minutes"',
  '{',
  '  "outcome": "Schedule a meeting with jane@acme.com",',
  '  "context": {',
  '    "who": "jane@acme.com",',
  '    "when": "tomorrow at 3pm",',
  '    "what": "call"',
  '  },',
  '  "provided": {',
  '    "attendee_email": "jane@acme.com",',
  '    "duration_minutes": 30,',
  '    "relative_time": "tomorrow at 3pm"',
  '  },',
  '  "success_criteria": "Meeting scheduled and attendee notified",',
  '  "confidence": 0.95',
  '}',
  '',
  '// User: "Draft follow-up emails for no-reply threads from the last 7 days"',
  '{',
  '  "outcome": "Create polite follow-up drafts for no-reply threads from the last 7 days",',
  '  "context": {',
  '    "what": "no-reply threads",',
  '    "when": "last 7 days",',
  '    "constraints": ["Only threads with no replies", "Timeframe: last 7 days"]',
  '  },',
  '  "provided": {',
  '    "days": 7',
  '  },',
  '  "success_criteria": "Polite follow-up drafts are created for all no-reply threads from the last 7 days",',
  '  "confidence": 0.95',
  '}',
  '',
  '// User: "Post to LinkedIn about our new feature"',
  '{',
  '  "outcome": "Create and publish a LinkedIn post about a new feature",',
  '  "context": {',
  '    "where": "LinkedIn",',
  '    "what": "post about new feature"',
  '  },',
  '  "provided": {',
  '    "platform": "linkedin",',
  '    "topic": "new feature"',
  '  },',
  '  "confidence": 0.8',
  '}',
  '',
  '// User: "Give me a {minutes=10}-minute triage of priority emails and create quick-reply drafts (max {max=8})."',
  '{',
  '  "outcome": "Triage priority emails from the last 10 minutes and create up to 8 quick-reply drafts",',
  '  "context": {',
  '    "what": "priority emails needing replies",',
  '    "when": "last 10 minutes",',
  '    "constraints": ["max 8 drafts", "quick replies"]',
  '  },',
  '  "provided": {',
  '    "time_window_minutes": 10,',
  '    "minutes": 10,',
  '    "max_results": 8,',
  '    "max": 8,',
  '    "action_type": "triage_and_draft"',
  '  },',
  '  "success_criteria": "Up to 8 draft replies created for priority emails from the last 10 minutes",',
  '  "confidence": 0.9',
  '}',
].join('\n');
