import { Link } from 'react-router-dom';

const sections = [
  {
    title: 'Acceptance of Terms',
    body:
      'These Terms of Service (“Terms”) govern your access to and use of Quik.day, including our website, APIs, automations, agents, documentation, and any content or services provided (collectively, the “Service”). By accessing or using the Service you agree to be bound by these Terms. If you are accepting on behalf of an organization, you represent that you have authority to bind that organization.',
  },
  {
    title: 'Eligibility & Accounts',
    body:
      'You must be at least 18 years old to create a Quik.day account. You are responsible for keeping your login credentials confidential and for all activity under your account. Notify us immediately if you suspect unauthorized access. We may disable accounts that violate these Terms.',
  },
  {
    title: 'Subscriptions & Payment',
    body:
      'Some features are free; others may require a paid plan. Fees, billing cycles, and usage limits are described in the ordering process. Unless stated otherwise, charges are non-refundable and renew automatically until canceled. You authorize us (or our payment processor) to store and continue billing your payment method. We may change pricing with prior notice; continued use constitutes acceptance.',
  },
  {
    title: 'Use of the Service',
    items: [
      'Do not misuse the Service, including probing, scanning, reverse engineering, or interfering with other users.',
      'Only submit data that you own or have the right to use, and ensure integrations comply with their provider terms.',
      'Do not use Quik.day to build or train competing models or products without our written consent.',
      'Respect applicable laws (export, privacy, IP, anti-spam). You are responsible for content generated by you or your agents.',
    ],
  },
  {
    title: 'Customer Data & Privacy',
    body:
      '“Customer Data” means data, instructions, files, and content that you submit to Quik.day. You retain ownership of Customer Data. We process it only to provide the Service, comply with law, and fulfill our Privacy Policy. You grant us and our subprocessors a worldwide, non-exclusive license to host, copy, and process Customer Data solely to provide the Service and related support.',
  },
  {
    title: 'Intellectual Property',
    body:
      'We (and our licensors) retain all rights in the Service, including software, documentation, trademarks, and feedback. Feedback you provide may be used without restriction. Outputs produced by Quik.day for you belong to you, but we make no guarantee they are error-free or suitable for every use. You are responsible for reviewing outputs before relying on them.',
  },
  {
    title: 'Beta Features & AI Content',
    body:
      'From time to time we may label functionality as beta, preview, or experimental. Such features are provided “as is,” may change or stop at any time, and are excluded from any uptime or support commitments. AI-generated content can be inaccurate or incomplete. Always review before acting.',
  },
  {
    title: 'Termination',
    body:
      'You may terminate your account at any time by contacting support or using workspace controls. We may suspend or terminate access if you breach these Terms, create risk, or fail to pay fees. Upon termination, you remain responsible for outstanding amounts. We will delete or return Customer Data according to our Privacy Policy and applicable law.',
  },
  {
    title: 'Disclaimers & Limitation of Liability',
    body:
      'The Service is provided “as is” without warranties of any kind, express or implied. To the fullest extent permitted by law, Quik.day disclaims implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Our total liability for any claim arising out of or relating to the Service is limited to the amounts paid by you to Quik.day in the twelve months preceding the event giving rise to the claim. We are not liable for indirect, incidental, special, consequential, or exemplary damages.',
  },
  {
    title: 'Indemnification',
    body:
      'You agree to defend, indemnify, and hold harmless Quik.day and its affiliates, directors, employees, and agents from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising from your use of the Service, Customer Data, or violation of these Terms.',
  },
  {
    title: 'Governing Law & Disputes',
    body:
      'These Terms are governed by the laws of the State of California, excluding its conflict-of-law rules. Any dispute will be resolved in the state or federal courts located in San Francisco County, California, and you consent to their jurisdiction. The United Nations Convention on Contracts for the International Sale of Goods does not apply.',
  },
  {
    title: 'Changes to These Terms',
    body:
      'We may update these Terms to reflect product or legal changes. If updates are material, we will provide notice via email or in-product messaging. Continued use after changes become effective constitutes acceptance. If you disagree, you must stop using the Service.',
  },
  {
    title: 'Contact',
    body:
      'Questions about these Terms? Emailquikday@oneway8x.com and we will be happy to help.',
  },
];

const TermsPage = () => {
  const effectiveDate = 'Effective November 17, 2025';

  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="border-b border-border bg-card/40">
        <div className="container mx-auto px-6 py-16 lg:py-20">
          <div className="space-y-6 max-w-3xl">
            <p className="text-sm uppercase tracking-[0.2em] text-muted-foreground">
              {effectiveDate}
            </p>
            <h1 className="text-4xl md:text-5xl font-bold">Quik.day Terms of Service</h1>
            <p className="text-lg text-muted-foreground">
              Please read these Terms carefully. They form a binding agreement between you and
              Quik.day regarding use of our products and services. If you do not agree, do not use
              Quik.day.
            </p>
            <div>
              <Link to="/" className="text-primary underline underline-offset-4">
                ← Back to homepage
              </Link>
            </div>
          </div>
        </div>
      </section>

      <section className="container mx-auto px-6 py-16 lg:py-24 space-y-12">
        {sections.map((section) => (
          <article
            key={section.title}
            className="rounded-3xl border border-border bg-card/60 px-6 py-6 md:px-10 md:py-8 shadow-sm"
          >
            <h2 className="text-2xl font-semibold mb-4">{section.title}</h2>
            {section.items ? (
              <ul className="list-disc list-inside space-y-2 text-muted-foreground leading-relaxed">
                {section.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            ) : (
              <p className="text-muted-foreground leading-relaxed">{section.body}</p>
            )}
          </article>
        ))}
        <div className="text-sm text-muted-foreground">
          Need something in writing (PO, DPA, MSLA exception)? Email{' '}
          <a className="underline" href="mailto:hello@quik.day">
           quikday@oneway8x.com
          </a>
          .
        </div>
      </section>
    </main>
  );
};

export default TermsPage;
